server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/namo_reservation
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet